site_name: k0da Documentation
site_description: A small CLI for creating and managing local Kubernetes clusters using k0s
site_url: https://makhov.github.io/k0da
repo_url: https://github.com/makhov/k0da
repo_name: makhov/k0da

theme:
  name: material
  logo: img/k0s-favicon-192.png
  favicon: img/k0s-favicon-192.png
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
      primary: blue
      accent: blue

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: blue
      accent: blue
  features:
    - toc.autohide
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.tabs.link
    - content.code.annotation
  language: en

plugins:
  - search

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Overview: index.md
  - Getting Started:
    - Installation: installation.md
    - Quick Start: quickstart.md
  - User Guide:
    - Creating Clusters: user-guide/creating-clusters.md
    - Configuration: user-guide/configuration.md
    - Managing Clusters: user-guide/managing-clusters.md
    - Loading Images: user-guide/loading-images.md
  - CLI Reference: cli/k0da.md
  - Examples: examples/basic.md
